name: Update data

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - name: Configure git to trust the workspace despite the different owner
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Get latest version from Leanny and update files
        run: python update.py

      - name: Commit data
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Sources/SplatDatabase/Resources/*.json
          git add update.py
          git add Sources/SplatDatabase/SplatDatabase.swift
          if test "$(git diff --name-only --cached 2>/dev/null | wc -l)" -gt "0" ; then git commit -m "Update data." && git push; else echo No changes found; fi
